### ISSUE TITLE
Game Crash: with version 1.9-3.1.0  on forge 1.9-12.16.0.1813-1.9

### ISSUE THREAD

**Issue by Kaisoul** [shadowfacts/ShadowMC#13]
Brief explanation of issue:
When player used an Anvil to repair game crashes
Steps to reproduce:
Place items in anvil to repair
- Step 1
- Step 2

Link to crash report (if applicable) on [gist](https://gist.github.com):
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (FastLeafDecay-MC1.9-1.2.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 3/30/16 9:48 AM
Description: Updating screen events

java.lang.IllegalAccessError: tried to access field net.minecraftforge.event.AnvilUpdateEvent.left from class net.shadowfacts.shadowmc.event.ShadowMCEventHandler
	at net.shadowfacts.shadowmc.event.ShadowMCEventHandler.anvilUpdate(ShadowMCEventHandler.java:25)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_29_ShadowMCEventHandler_anvilUpdate_AnvilUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.common.ForgeHooks.onAnvilChange(ForgeHooks.java:801)
	at net.minecraft.inventory.ContainerRepair.func_82848_d(ContainerRepair.java:169)
	at net.minecraft.inventory.ContainerRepair.func_75130_a(ContainerRepair.java:141)
	at net.minecraft.inventory.ContainerRepair$1.func_70296_d(ContainerRepair.java:47)
	at net.minecraft.inventory.InventoryBasic.func_70299_a(SourceFile:108)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:298)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:518)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:630)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:596)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:550)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:509)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1694)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.shadowfacts.shadowmc.event.ShadowMCEventHandler.anvilUpdate(ShadowMCEventHandler.java:25)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_29_ShadowMCEventHandler_anvilUpdate_AnvilUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.common.ForgeHooks.onAnvilChange(ForgeHooks.java:801)
	at net.minecraft.inventory.ContainerRepair.func_82848_d(ContainerRepair.java:169)
	at net.minecraft.inventory.ContainerRepair.func_75130_a(ContainerRepair.java:141)
	at net.minecraft.inventory.ContainerRepair$1.func_70296_d(ContainerRepair.java:47)
	at net.minecraft.inventory.InventoryBasic.func_70299_a(SourceFile:108)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:298)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:518)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:630)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:596)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:550)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:509)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiRepair

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Kaisoul'/334, l='MpServer', x=-273.25, y=70.00, z=-1977.69]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-232,64,200), Chunk: (at 8,4,8 in -15,12; contains blocks -240,0,192 to -225,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1058179 game time, 2380 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 105 total; [EntityBat['Bat'/522, l='MpServer', x=-251.36, y=47.10, z=-1992.89], EntityHorse['Horse'/524, l='MpServer', x=-248.34, y=61.78, z=-1953.58], EntitySquid['Squid'/525, l='MpServer', x=-248.41, y=61.84, z=-1949.40], EntityCreeper['Creeper'/8461, l='MpServer', x=-340.53, y=28.00, z=-1948.84], EntityHorse['Horse'/528, l='MpServer', x=-235.96, y=64.00, z=-1981.07], EntityBat['Bat'/4112, l='MpServer', x=-263.25, y=36.10, z=-2027.20], EntityHorse['Horse'/530, l='MpServer', x=-249.30, y=62.35, z=-1945.40], EntitySkeleton['Skeleton'/8978, l='MpServer', x=-293.50, y=25.00, z=-1994.50], EntityHorse['Horse'/533, l='MpServer', x=-236.10, y=63.00, z=-1937.04], EntityHorse['Horse'/534, l='MpServer', x=-234.91, y=63.00, z=-1948.01], EntityHorse['Horse'/535, l='MpServer', x=-230.12, y=63.00, z=-1946.90], EntityBat['Bat'/10520, l='MpServer', x=-261.53, y=32.28, z=-2021.31], EntityHorse['Horse'/541, l='MpServer', x=-244.01, y=66.00, z=-2035.85], EntityCreeper['Creeper'/7453, l='MpServer', x=-222.59, y=64.57, z=-1986.86], EntityHorse['Horse'/542, l='MpServer', x=-242.22, y=63.11, z=-1919.04], EntityHorse['Horse'/547, l='MpServer', x=-230.97, y=65.00, z=-2039.25], EntitySkeleton['Skeleton'/10789, l='MpServer', x=-239.99, y=41.00, z=-2047.59], EntityZombie['Zombie'/10790, l='MpServer', x=-242.29, y=41.00, z=-2047.51], EntityZombie['Zombie'/10791, l='MpServer', x=-240.98, y=41.00, z=-2046.42], EntityZombie['Zombie'/10792, l='MpServer', x=-243.48, y=42.00, z=-2042.27], EntityCreeper['Creeper'/7209, l='MpServer', x=-328.50, y=39.00, z=-1953.50], EntityCreeper['Creeper'/10282, l='MpServer', x=-242.50, y=22.00, z=-1964.50], EntityHorse['Horse'/558, l='MpServer', x=-216.09, y=65.00, z=-2042.08], EntitySkeleton['Skeleton'/7986, l='MpServer', x=-310.50, y=18.00, z=-1987.50], EntityZombie['Zombie'/9778, l='MpServer', x=-303.50, y=24.00, z=-1992.50], EntityZombie['Zombie'/9781, l='MpServer', x=-294.50, y=16.00, z=-1980.50], EntityVillager['Villager'/311, l='MpServer', x=-312.70, y=68.00, z=-2028.76], EntityVillager['Villager'/312, l='MpServer', x=-312.70, y=71.00, z=-2026.49], EntityVillager['Villager'/313, l='MpServer', x=-312.35, y=68.00, z=-2026.65], EntityVillager['Villager'/314, l='MpServer', x=-308.09, y=71.00, z=-2025.61], EntityVillager['Villager'/315, l='MpServer', x=-312.00, y=68.00, z=-2028.49], EntityVillager['Villager'/316, l='MpServer', x=-310.65, y=71.00, z=-2028.49], EntityVillager['Villager'/317, l='MpServer', x=-313.29, y=68.00, z=-2030.50], EntityZombie['Zombie'/5693, l='MpServer', x=-235.50, y=10.00, z=-1927.50], EntityCreeper['Creeper'/11325, l='MpServer', x=-293.50, y=47.00, z=-2051.50], EntityVillager['Villager'/318, l='MpServer', x=-312.70, y=71.00, z=-2027.17], EntityZombie['Zombie'/11326, l='MpServer', x=-293.50, y=47.00, z=-2051.50], EntityVillager['Villager'/319, l='MpServer', x=-311.89, y=68.00, z=-2027.38], EntityVillager['Villager'/320, l='MpServer', x=-311.35, y=71.00, z=-2028.62], EntityIronGolem['Iron Golem'/321, l='MpServer', x=-313.25, y=67.00, z=-2022.93], EntityVillager['Villager'/322, l='MpServer', x=-310.63, y=67.00, z=-2022.59], EntityVillager['Villager'/323, l='MpServer', x=-312.70, y=71.00, z=-2028.70], EntityVillager['Villager'/324, l='MpServer', x=-312.70, y=71.00, z=-2029.47], EntityVillager['Villager'/325, l='MpServer', x=-311.18, y=71.00, z=-2027.79], EntityVillager['Villager'/326, l='MpServer', x=-312.70, y=71.00, z=-2028.04], EntityVillager['Villager'/327, l='MpServer', x=-311.73, y=71.00, z=-2024.93], EntityVillager['Villager'/328, l='MpServer', x=-311.98, y=71.00, z=-2028.70], EntityVillager['Villager'/329, l='MpServer', x=-312.70, y=68.00, z=-2029.51], EntityVillager['Villager'/330, l='MpServer', x=-313.32, y=71.00, z=-2030.58], EntityIronGolem['Iron Golem'/331, l='MpServer', x=-311.73, y=67.00, z=-2023.30], EntityCreeper['Creeper'/587, l='MpServer', x=-223.50, y=37.00, z=-2048.50], EntityVillager['Villager'/332, l='MpServer', x=-307.32, y=71.00, z=-2024.93], EntityBat['Bat'/10828, l='MpServer', x=-256.11, y=36.16, z=-2041.12], EntityVillager['Villager'/333, l='MpServer', x=-307.17, y=71.00, z=-2025.70], EntityBat['Bat'/10829, l='MpServer', x=-258.14, y=36.58, z=-2031.05], EntityBat['Bat'/8526, l='MpServer', x=-260.34, y=31.82, z=-1968.46], EntityBat['Bat'/9553, l='MpServer', x=-236.72, y=53.03, z=-2038.39], EntityHorse['Horse'/597, l='MpServer', x=-202.86, y=67.00, z=-1925.06], EntityCreeper['Creeper'/6236, l='MpServer', x=-325.50, y=32.00, z=-1919.50], EntityEnderman['Enderman'/7262, l='MpServer', x=-242.50, y=22.00, z=-1954.50], EntityZombie['Zombie'/7775, l='MpServer', x=-232.50, y=24.00, z=-2040.50], EntitySkeleton['Skeleton'/7266, l='MpServer', x=-260.50, y=22.00, z=-1970.50], EntityZombie['Zombie'/7525, l='MpServer', x=-204.50, y=22.00, z=-2029.50], EntitySkeleton['Skeleton'/9575, l='MpServer', x=-328.50, y=41.00, z=-1958.50], EntityCreeper['Creeper'/9576, l='MpServer', x=-305.50, y=50.00, z=-1919.50], EntityZombie['Zombie'/8046, l='MpServer', x=-340.50, y=41.00, z=-1969.50], EntitySpider['Spider'/7793, l='MpServer', x=-255.50, y=36.00, z=-2045.50], EntitySkeleton['Skeleton'/7795, l='MpServer', x=-258.50, y=36.00, z=-2040.50], EntityBat['Bat'/8325, l='MpServer', x=-329.39, y=37.12, z=-1935.52], EntityCreeper['Creeper'/8594, l='MpServer', x=-261.50, y=30.00, z=-2007.50], EntityCreeper['Creeper'/8595, l='MpServer', x=-262.50, y=30.00, z=-2010.50], EntityWitch['Witch'/9365, l='MpServer', x=-329.50, y=23.00, z=-1944.50], EntityPlayerSP['Kaisoul'/334, l='MpServer', x=-273.25, y=70.00, z=-1977.69], EntityCreeper['Creeper'/1942, l='MpServer', x=-206.50, y=40.00, z=-2053.50], EntityCreeper['Creeper'/10402, l='MpServer', x=-227.50, y=24.00, z=-1956.50], EntityCreeper['Creeper'/8867, l='MpServer', x=-259.50, y=36.00, z=-1974.50], EntityBat['Bat'/10148, l='MpServer', x=-226.98, y=59.10, z=-2042.82], EntitySkeleton['Skeleton'/11177, l='MpServer', x=-197.50, y=28.00, z=-2043.50], EntityCreeper['Creeper'/6320, l='MpServer', x=-303.50, y=26.00, z=-2002.50], EntityCreeper['Creeper'/6321, l='MpServer', x=-305.50, y=26.00, z=-2004.50], EntityCreeper['Creeper'/10162, l='MpServer', x=-240.50, y=22.00, z=-1972.50], EntityCreeper['Creeper'/10163, l='MpServer', x=-239.50, y=22.00, z=-1971.50], EntityZombie['Zombie'/6068, l='MpServer', x=-264.65, y=35.00, z=-2027.65], EntityCreeper['Creeper'/10164, l='MpServer', x=-246.22, y=22.00, z=-1976.44], EntitySpider['Spider'/10423, l='MpServer', x=-307.30, y=18.10, z=-1979.30], EntityCreeper['Creeper'/7609, l='MpServer', x=-217.50, y=36.00, z=-2006.50], EntityZombie['Zombie'/11194, l='MpServer', x=-194.50, y=27.00, z=-2041.50], EntityHorse['Horse'/443, l='MpServer', x=-282.00, y=69.00, z=-1978.97], EntityZombie['Zombie'/11195, l='MpServer', x=-195.50, y=27.00, z=-2042.50], EntityHorse['Donkey'/444, l='MpServer', x=-282.16, y=69.00, z=-1983.15], EntitySkeleton['Skeleton'/11196, l='MpServer', x=-194.50, y=27.00, z=-2040.50], EntityCreeper['Creeper'/10431, l='MpServer', x=-254.50, y=51.00, z=-1987.50], EntityItemFrame['entity.ItemFrame.name'/448, l='MpServer', x=-261.50, y=71.50, z=-1985.03], EntityItemFrame['entity.ItemFrame.name'/449, l='MpServer', x=-263.50, y=71.50, z=-1985.03], EntityMinecartEmpty['entity.MinecartRideable.name'/450, l='MpServer', x=-274.49, y=60.06, z=-1992.50], EntityCreeper['Creeper'/451, l='MpServer', x=-325.50, y=42.00, z=-1969.50], EntityHorse['Horse'/461, l='MpServer', x=-331.88, y=64.00, z=-1900.92], EntityHorse['Horse'/465, l='MpServer', x=-313.89, y=63.00, z=-1987.01], EntityHorse['Horse'/469, l='MpServer', x=-304.05, y=62.00, z=-1946.04], EntitySquid['Squid'/7397, l='MpServer', x=-238.90, y=61.31, z=-1938.89], EntityCreeper['Creeper'/9192, l='MpServer', x=-263.50, y=30.00, z=-2010.50], EntitySkeleton['Skeleton'/9199, l='MpServer', x=-319.50, y=26.00, z=-1932.50], EntityBat['Bat'/4348, l='MpServer', x=-335.25, y=30.10, z=-1942.45], EntityBat['Bat'/3069, l='MpServer', x=-323.33, y=29.00, z=-1920.91], EntityBat['Bat'/10493, l='MpServer', x=-283.25, y=17.08, z=-1995.84]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:453)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2647)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:387)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2155432760 bytes (2055 MB) / 4084727808 bytes (3895 MB) up to 4084727808 bytes (3895 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4078M -Xms4078M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 99
	FML: MCP 9.23 Powered by Forge 12.16.0.1813 Optifine OptiFine_1.9_HD_U_B1 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.0.1813-1.9.jar) 
	UCHIJAAAA	Forge{12.16.0.1813} [Minecraft Forge] (forge-1.9-12.16.0.1813-1.9.jar) 
	UCHIJAAAA	BetterAchievements{0.2.1} [Better Achievements] (BetterAchievements-1.9-0.2.1.jar) 
	UCHIJAAAA	enderbook{1.0.3} [Ender Book] (EnderBook-1.9-1.0.3.jar) 
	UCHIJAAAA	EzTimeKeeper{2.1.3} [Time Keeper] (eztimekeeper-2.1.3.jar) 
	UCHIJAAAA	FastLeaveDecay{1.1} [Fast Leave Decay] (FastLeafDecay-MC1.9-1.2.jar) 
	UCHIJAAAA	ism{1.0.2e} [Instant Structures Mod (ISM)] (ism-1.0.2e.jar) 
	UCHIJAAAA	JEI{3.1.2.172} [Just Enough Items] (jei_1.9-3.1.2.172.jar) 
	UCHIJAAAA	journeymap{1.9-5.1.6b1} [JourneyMap] (journeymap-1.9-5.1.6b1-unlimited.jar) 
	UCHIJAAAA	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.2-5.jar) 
	UCHIJAAAA	Psi{beta-29} [Psi] (Psi-beta-29.jar) 
	UCHIJAAAA	recycler{1.0} [Recycleur] (recycler-1.1.1.jar) 
	UCHIJAAAA	shadowmc{3.1.0} [ShadowMC] (ShadowMC-1.9-3.1.0.jar) 
	UCHIJAAAA	terrariabuttons{1.0.1} [Terraria Buttons] (TerrariaButtons-1.9-1.0.1.jar) 
	UCHIJAAAA	timehud{5.0.2.12} [Time HUD] (TimeHUD-5.0.2.12.jar) 
	UCHIJAAAA	timehudvc{2.1} [Time HUD Version Checker] (TimeHUD-5.0.2.12.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (FastLeafDecay-MC1.9-1.2.jar)
  lumien.fastleavedecay.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 364.51' Renderer: 'GeForce GTX 550 Ti/PCIe/SSE2'
	Launched Version: 1.9-forge1.9-12.16.0.1813-1.9
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 550 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 364.51, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: PureBDcraft 128x MC19.zip, Kaisoul 1.9.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD FX(tm)-4300 Quad-Core Processor 
	OptiFine Version: OptiFine_1.9_HD_U_B1
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 364.51
	OpenGlRenderer: GeForce GTX 550 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4`
```
ShadowMC version:
1.9-3.1.0
Minecraft version:

forge 1.9-12.16.0.1813-1.9

**Comment by shadowfacts** [comment]
I'll release a fix for this however there may be more problems as Forge for 1.9 is still very unstable.

**Comment by shadowfacts** [comment]
a22edcb26a1d18355ac769bd29dcd3fc893d51c0

**Comment by shadowfacts** [comment]
http://minecraft.curseforge.com/projects/shadowmc/files/2291267
